channels:
  gotify:
    domain: "https://gotify.test.org"
    key: "your_key"
  matrix:
    domain: "https://matrix.org:8008"
    room_id: "!tRdaaseeJgTOmvinGWe:matrix.org:8008"
    access_token: "syt_cm223dQ_bcMIld238DSCodH_0IVVKN"
  telegram:
    api_token: "5190222484:AAHb32DSFxqetzdOupqF6Lo"
    chat_id: "-9328751"
  discord:
    webhook_url: "https://discord.com/api/webhooks/your/webhook/url"
    bot_name: "echGo"
  trello:
    key: "a4cbc8cf6c409fc385633c1b120"
    token: "d7b223825fdsfe762f1cb1f18e9d238f3013efd7d43080"
    id_list: "692231232fc25b8db569d"
  smtp:
    host: "mail.server.com"
    port: 465
    username: "mail@mail.org"
    password: "your_passwors"
    email_recipient: "info@other-mail.com"
  webhook:
    domain: "https://webhook.site/9ea0-4f5f-b1d2-38e107bbbd07?"