version: "3.5"
services:
    echgo:
        container_name: echgo
        networks:
            - echgo_org
        environment:
            - TZ=Europe/Berlin
        volumes:
            - /etc/echgo/configuration:/app/files/configuration
            - /var/lib/echgo/notification:/app/files/notification
        labels:
            - com.centurylinklabs.watchtower.enable=true
        restart: always
        image: echgo/echgo:latest
    watchtower:
        container_name: watchtower
        networks:
            - echgo_org
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - 8080
        depends_on:
            - echgo
        restart: always
        image: containrrr/watchtower:latest
        command: --cleanup --include-restarting --rolling-restart --include-stopped --label-enable --interval 3600
networks:
    echgo_org:
        driver: bridge