name: CompVer

on:
    push:
        tags:
            - "v*.*.*"

env:
    USER_NAME: "GitHub Action"
    USER_EMAIL: "actions@github.com"
    DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    COMMIT_MESSAGE: "ci: The data of the master branch was merged automatically."

jobs:
    version:
        runs-on: ubuntu-latest
        steps:

            - name: Clone repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set repository tag information
              id: information
              run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

            - name: Get the major version
              id: compver
              uses: gowizzard/compver@v3.1.2
              with:
                  args: "-core -block major -version1 ${{ steps.information.outputs.tag }}"

            - name: Set git config
              run: |
                  git config --local user.name "$USER_NAME"
                  git config --local user.email "$USER_EMAIL"

            - name: Merge data from default branch
              run: |
                  git fetch
                  git checkout v${{ steps.compver.outputs.number }}
                  git pull
                  git merge --no-ff "origin/$DEFAULT_BRANCH" -m "$COMMIT_MESSAGE"
                  git push