name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello, thank you for sending us your suggestions or comments. We will try to answer them as soon as possible.'
        pr-message: 'Hello, thank you for your first pull request. We will try to look at this as soon as possible.'
