name: Makefile CI

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:

            - name: Clone repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Create Docker Buildx
              run: docker buildx create --use

            - name: Build Docker Image
              run: make docker-build

            - name: Push Image to Docker Hub
              run: make docker-push